# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mernNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mernNative
  pod 'Stripe', '~> 14.0.0'

  target 'mernNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mernNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
